---
name: Andrea
surname: Vargas
position: "Estudiante de Estadística"
address: "San José, Costa Rica"
phone: +506 7131 7925
www: 
email: "avargas2398@gmail.com"
twitter: andreavargasmon
github: andreavargasmontero
linkedin: andreavargasmontero
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::latexcv:
    theme: classic
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Educación

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Date, ~ Institution, ~ Where,
  "Secundaria", "2012-2016", "Liceo Bilingüe de Naranjo", "Naranjo, Alajuela, 
  Costa Rica",
  "Bachillerato en Estadística - Grad. de honor", "2017-2020", 
  "Universidad de Costa Rica", "San José, Costa Rica",
) %>% 
  detailed_entries(Degree, Date, Institution, Where)
```

# Habilidades
```{r}
tribble(
  ~Skill, ~Level,
  "R", "Intermedio avanzado",
  "Python", "Intermedio",
  "SQL", "Intermedio",
  "HTML", "Básico",
  "CSS", "Básico",
  "GIS", "Básico",
  "EViews", "Básico"
  
) %>% 
  detailed_entries(Skill, Level)
```

# Experiencia
```{r}
tribble(
  ~Date, ~Job, ~Company, ~Task,
  "2018", "Asistente académica", "Phd. J. Antonio Rodríguez", "Investigación",
  "Ene 2019 - Dic 2020", "Asistente académica", "Msc. Ricardo Alvarado", "Proyecto: Utilizando juegos para enseñar Regresión Lineal",
  "Ene 2019 - Dic 2020", "Asistente académica", "Phd. Marcela Alfaro", "Calificar asignaciones, organización de aplicaciones shiny, planeación de cursos",
  "Ene 2019 - Dic 2020", "Asistente académica", "Msc. Ericka Méndez", "Calificar asignaciones y planeación de cursos",
  "Nov 2019 - Dic 2020", "Pasante", "ixpantia", "Tutoriales interactivos en R con gradethis y learnr y dashboard de gestión de proyectos en shiny",
  "Jun 2020 - Dic 2020", "Asistente de investigación", "CeNaT", "Análisis exploratorio y de texto, Proyecto industria 4.0",
  "Ene 2021 - Hoy", "Científica de datos", "ixpantia", "Enseñanza, modelado, 
  manejo de bases de datos, análisis de datos"
) %>% 
  detailed_entries(Date, Job, Company, Task)
```

# Otros proyectos

```{r}
tribble(
  ~Date, ~Task, ~Description,
  "2019 - Presente", "RLadies SJ CR Co-Organizadora", "Planificar y exponer sesiones y acividades varias",
  "2019 - Presente", "Editora de la Revista Serengeti", "Revisión de artículos, organización and publicación",
  "2021 - Presente", "Data Latam Co-Organizadora", "Planificar webinarios, podcasts y publicación en redes"
) %>% 
  detailed_entries(Date, Task, Description)
```
