---
name: Andrea
surname: Vargas
position: "Statistics Student"
address: "San José, Costa Rica"
phone: +506 7131 7925
www: 
email: "avargas2398@gmail.com"
twitter: andreavargasmon
github: andreavargasmontero
linkedin: andreavargasmontero
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::latexcv:
    theme: classic
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Date, ~ Institution, ~ Where,
  "Highschool", "2012-2016", "Bilingual Highscholl of Naranjo", "Naranjo, Alajuela, Costa Rica",
  "Bachelor in Statistics - Honor Grad", "2017-2020", "Universidad de Costa Rica", "San José, Costa Rica",
) %>% 
  detailed_entries(Degree, Date, Institution, Where)
```

# Skills
```{r}
tribble(
  ~Skill, ~Level,
  "R programming", "Intermediate/Advanced",
  "Python", "Intermediate",
  "SQL", "Intermediate",
  "HTL", "Basic",
  "CSS", "Basic",
  "GIS", "Basic",
  "EViews", "Basic"
) %>% 
  detailed_entries(Skill, Level)
```

# Experience
```{r}
tribble(
  ~Date, ~Job, ~Company, ~Task,
  "2018", "Academic assistant", "Phd. J. Antonio Rodríguez", "Investigation",
  "2019 - Present", "Academic assistant", "Msc. Ricardo Alvarado", "Project: Using games to teach Linear Regression",
  "2019 - Present", "Academic assistant", "Phd. Marcela Alfaro", "Review quizzes, traductions, shiny apps, course planning",
  "2019 - Present", "Academic assistant", "Msc. Ericka Méndez", "Review quizzes, shiny apps, course planning and others",
  "Nov 2019 - Present", "Intern", "ixpantia", "Interactive tutorials with learnr+gradethis and project management dashboard with shiny",
  "Jun 2020 - Dic 2020", "Investigation assistant", "CeNaT", "Text exploratory data analysis, Project: 4.0 industry",
  "Ene 2021 - Hoy", "Data scientist", "ixpantia", "Teaching, modelling, 
  database management, data analysis"
) %>% 
  detailed_entries(Date, Job, Company, Task)
```

# Other projects

```{r}
tribble(
  ~Date, ~Task, ~Description,
  "2019 - Present", "RLadies SJ CR Co-Organizer", "Plan and teach sessions, presentations and partnerships",
  "2019 - Present", "Revista Serengeti Editing Team", "Reviewing papers, organization and publication",
  "2021 - Present", "Data Latam Co-Organizer", "Plan webinars and podcasts, social media"
) %>% 
  detailed_entries(Date, Task, Description)
```

