---
name: Andrea
surname: Vargas
position: "Data Scientist"
address: "San José, Costa Rica"
phone: +506 7131 7925
www: 
email: "avargas2398@gmail.com"
twitter: andreavargasmon
github: andreavargasmontero
linkedin: andreavargasmontero
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

# Education

```{r}
tribble(
  ~degree, ~date, ~institution, ~where,
  "Highschool", "2012-2016", "Bilingual Highscholl of Naranjo", "Naranjo, Alajuela, Costa Rica",
  "Honors Bachelor in Statistics", "2017-2020", "Universidad de Costa Rica", "San José, Costa Rica",
) %>% 
  detailed_entries(what = degree, 
                   when = date, 
                   with = institution, 
                   whe = where,
                   why = NULL)
```

# Skills
```{r}
tribble(
  ~skill, ~level,
  "R", "Advanced",
  "Python", "Intermediate",
  "SQL", "Advanced",
  "HTML-CSS", "Intermediate",
  "Domo", "Advanced",
) %>% 
  detailed_entries(what = skill, level)
```

# Experience
```{r}
tribble(
  ~date, ~job, ~company, ~task,
  "2018", "Academic assistant", "Phd. J. Antonio Rodríguez", "Investigation",
  "2019 - 2020", "Academic assistant", "Msc. Ricardo Alvarado", "Project: Using games to teach Linear Regression",
  "2019 - 2020", "Academic assistant", "Phd. Marcela Alfaro", "Review quizzes, traductions, shiny apps, course planning",
  "2019 - 2020", "Academic assistant", "Msc. Ericka Méndez", "Review quizzes, shiny apps, course planning and others",
  "2020", "Intern", "CENAT", "Research assistant - NLP Project",
  "2019 - 2020", "Intern", "ixpantia", "Interactive tutorials with learnr+gradethis and project management dashboard with shiny",
  "2021 - Present", "Data professional", "ixpantia", "Data consultant to organizations
  from a variety of fields. Tasks range from data transformation, Exploratory Data Analysis, automatic reporting, data wrangling, to data visualization and dashboards, machine learning and statistical modelling, API development, cloud based deployments and dataflows"
) %>% 
  detailed_entries(when = date, 
                   what = job, 
                   with = company, 
                   why = task)
```

\newpage

# Other projects

```{r}
tribble(
  ~date, ~project, ~description,
  "2019 - Present", "RLadies SJO CR Co-Organizer", "Plan y teach sessions and other activities",
  "2019 - 2022", "Revista Serengeti Editor Team", "Paper revision, general organization and publication",
  "2022", "Professor of data visualization best practices course", "At Universidad de Costa Rica"
) %>% 
  detailed_entries(when = date, 
                   what = project, 
                   why = description)
```
